### ISSUE TITLE
Trying to go onto mexican train site

### ISSUE THREAD

**Issue by Bombardier-C-Kram** [PeteyPii/MexicanTrain#1]
When I load the page, i get: 
./common/GameSettingsWrapper.js
Module not found: Can't resolve '../gen/GameSettings_pb' in '/home/spacequacker/Desktop/Projects/MexicanTrain-master/website/common'
I also cant do the npm build script because the command protoc is not found.

**Comment by PeteyPii** [comment]
The site is a WIP I never put enough time into finishing. The error you getting is due to not installing the protocol buffer compiler.
